### ISSUE TITLE
RateLimits not being applied with external redis

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#1013]
**Expected**

RLP applied and for requests to be ratelimited
This worked well when not using an external redis
I expected it to keep working after updating the limitador CR to add a redis storage credential. Instead rate limitis stop being applied, even though the policy is marked as enforced and kuadrant is marked as ready.

**Reproduce**

- Deployment was across two clusters using v1-rc4
- Updated Limitador CRD in both clusters to have a valid credential ref: 
``` yaml
spec:
  storage:
    redis:
      configSecretRef:
        name: redis-credentials 
```
 - Kuadrant became ready and the RLP remained in an enforced state but my curl requests continued to always return 200
 
RateLimitPolicy used : 

```yaml
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: gw-rlp
  labels:
    policy: 'gateway'
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: external
  limits:
    'global':
      rates:
        - limit: 5
          window: 10s
```

**Comment by maleck13** [comment]
@alexsnaps FYI

**Comment by maleck13** [comment]
@jsmolar @averevki do we have additional tests covering use of external redis? Would like to cover it to see is this an actual issue or something unique to my setup

**Comment by trepel** [comment]
@maleck13 we aim to have manual test scenario for this. Unfortunately it is not finalized yet. I tried this myself and I was not able to make it work either.  However, I did test the external redis (aws elasticache) back in April so quite a long time ago, there have been a lot of changes since then so I could easily make some user error. I will try again tomorrow but for now I would say that we should treat this as a real issue.

**Comment by alexsnaps** [comment]
Also, it is worth mentioning that the Kuadrant-operator will default (tho, I think it can't be configured any other way as of now) to [configure the wasm-shim to allow request through on failures to talk to Limitador](https://github.com/Kuadrant/kuadrant-operator/blob/main/pkg/wasm/utils.go#L42) (or that error'ing out because of that not being able to talk to the configured Redis). So it's important to gather logs from these participants when things fail here in that very way, as this is the expected behavior in the face of configuration/transient issues...

**Comment by trepel** [comment]
@alexsnaps I am sorry for not being clear enough.

Yes, there are automated tests around Ratelimiting - along the lines of creating RLP and ensuring 429 is returned after expected no. of requests, but only with trivial (empty `.spec`) Limitador CR. Back in April I tested Kuadrant with AWS Elasticache but I used `.redis-cached`. I am not aware of any testing of non-cached Redis being done by QE.

Today I tried this more thoroughly. By "this" I mean creating a new OCP cluster in AWS. Installing Kuadrant v1 rc4 there. Setting up GW, HTTPRoutes, policies etc and making sure it works, including RLPs (429s returned as expected). Then I created Elasticache instance in cluster's VPC, removed RLPs and updaded Limitador CR (`.spec.storage.redis.configSecretRef.name`) so that it uses Elasticache instance for persistence. I recreated the RLPs and tried again. This time I got 429s as expected so it seems it works just fine.
Not sure what I did wrong yesterday.

**Comment by maleck13** [comment]
thanks @trepel I am going to re-test locally here and see do I hit the issue again also. Will provide more details if I do.

**Comment by trepel** [comment]
yw, fyi, I connected to my elasticache instance and I can see the key for my RLP limit there:
````
keys *
1) "namespace:{scale-test-0/httproute-gw1-l1-i0},counters_of_limit:{\"namespace\":\"scale-test-0/httproute-gw1-l1-i0\",\"seconds\":10,\"conditions\":[\"limit.httproute_level__1b8e78f8 == \\\"1\\\"\"],\"variables\":[]}"
```

**Comment by alexsnaps** [comment]
👌 Awesome... and again, @maleck13, if something "isn't working", please look into the `Limitador` CR to see if it reflects the changes you'd expect, and the logs of your limitador pod and envoy... As @trepel points out, looking into the Redis(-alike) is certainly one way to validate things are fine.

**Comment by maleck13** [comment]
I don't think we should expect the ratelimitpolicy to be removed if the storage changes in limitador?

**Comment by alexsnaps** [comment]
Yeah, removing the RLP shouldn't be a requirement... Again, other that event triggering something "else", there is also no need for it... It all should trigger the `Limitador` CR to be updated. Changing the storage, unlike adding & removing limits, requires the Limitador process/pod to be restarted tho

**Comment by maleck13** [comment]
Before RLP applied

redis keys
KEYS *
(empty array

After RLP applied and Limitador updated

1) "namespace:{gateway-system/toystore},counters_of_limit:{\"namespace\":\"gateway-system/toystore\",\"seconds\":10,\"conditions\":[\"limit.global__dc30d66c == \\\"1\\\"\"],\"variables\":[]}"
2) "namespace:{gateway-system/toystore},counter:{\"limit\":{\"namespace\":\"gateway-system/toystore\",\"seconds\":10,\"conditions\":[\"limit.global__dc30d66c == \\\"1\\\"\"],\"variables\":[]},\"set_variables\":{},\"remaining\":null,\"expires_in\":null}"

So I will close this as cannot reproduce. I am not sure what the issue was unfortuantely with the previous install...

**Comment by maleck13** [comment]
Adding as much context as I can. I don't know right now what in the stack isn't working:  The Limitador CR reports no issues and the kuadrant-operator does not report any issues in the logs

```
# BEFORE APPLYING STORAGE
apiVersion: limitador.kuadrant.io/v1alpha1
kind: Limitador
metadata:
  name: limitador
  namespace: kuadrant-system
spec:
  limits:
  - conditions:
    - limit.global__f63bec56 == "1"
    max_value: 5
    namespace: gateway-system/toystore
    seconds: 10
    variables: []
status:
  conditions:
  - lastTransitionTime: "2024-11-13T12:18:13Z"
    message: Limitador is ready
    reason: Ready
    status: "True"
    type: Ready
  observedGeneration: 2
  service:
    host: limitador-limitador.kuadrant-system.svc.cluster.local
    ports:
      grpc: 8081
      http: 8080

--- 
#AFTER APPLYING STORAGE
apiVersion: limitador.kuadrant.io/v1alpha1
kind: Limitador
metadata:
  name: limitador
  namespace: kuadrant-system
spec:
  limits:
  - conditions:
    - limit.global__f63bec56 == "1"
    max_value: 5
    namespace: gateway-system/toystore
    seconds: 10
    variables: []
  storage:
    redis:
      configSecretRef:
        name: redis-credentials
status:
  conditions:
  - lastTransitionTime: "2024-11-14T08:40:18Z"
    message: Limitador is ready
    reason: Ready
    status: "True"
    type: Ready
  observedGeneration: 3
  service:
    host: limitador-limitador.kuadrant-system.svc.cluster.local
    ports:
      grpc: 8081
      http: 8080
```


The limitador operator also does not seem to have an issue when I add or remove the configuration for storage other than the occasional :
```
 the object has been modified; please apply your changes to the latest version and try again. Which is a common error in controllers
``` 

```
limitador-operator-controller-manager-6687869587-sqzmr manager {"level":"info","ts":"2024-11-14T08:47:07Z","logger":"limitador","msg":"update object","limitador":{"name":"limitador","namespace":"kuadrant-system"},"GKV":"apps/v1, Kind=Deployment","name":"limitador-limitador","namespace":"kuadrant-system"}
limitador-operator-controller-manager-6687869587-sqzmr manager {"level":"info","ts":"2024-11-14T08:47:07Z","logger":"limitador","msg":"successfully reconciled","limitador":{"name":"limitador","namespace":"kuadrant-system"}}
```
