### ISSUE TITLE
Some custom response return codes in AuthPolicy do not work

### ISSUE THREAD

**Issue by averevki** [Kuadrant/kuadrant-operator#1022]
When I set custom response return codes in AuthPolicy, I'm not sure why, but it can't send the response back now. Curl shows `Unsupported HTTP/1 subversion in response` as there is a wrong HTTP protocol version used. `httpcore.RemoteProtocolError: illegal status line: bytearray(b'HTTP/1.1 0 Unknown')` this is from the python library. 

Seems like the issue remains only when specifying code that doesn't have any purpose by the standard (e.g. code 431 works, but 430 does not)

AuthPolicy:
```yaml
spec:
  rules:
    authentication:
      default:
        credentials:
          authorizationHeader:
            prefix: Bearer
        jwt:
          issuerUrl: 'http://1.2.3.4:8080/realms/realm-averevki--hbxe'
          ttl: 0
        metrics: false
        priority: 0
    authorization:
      Whitelist:
        metrics: false
        patternMatching:
          patterns:
            - operator: eq
              selector: context.request.http.path
              value: /allow
        priority: 0
    response:
      unauthenticated:
        code: 333
      unauthorized:
        code: 444
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: route-averevki--lhhk
```
<details>
<summary>Gateway</summary>

```yaml
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: '*.apps.kua.redhat.com'
      name: api
      port: 80
      protocol: HTTP
```
</details>

<details>
<summary>HTTPRoute</summary>

```yaml
spec:
  hostnames:
    - hostname-averevki--zwt-kuadrant.apps.kua.redhat.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gw-averevki--st7
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: httpbin-averevki--v8n
          namespace: kuadrant
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
```
</details>
