### ISSUE TITLE
Incorrect `status.condition` Message When `spec.limil is Missing in RLP

### ISSUE THREAD

**Issue by jsmolar** [Kuadrant/kuadrant-operator#1023]
When a RateLimitPolicy (RLP) is created without specifying spec.limi, the status.condition shows the following message:

```yaml
- lastTransitionTime: '2024-11-14T12:54:54Z'
  message: RateLimitPolicy is not in the path to any existing routes
  reason: Unknown
  status: 'False'
  type: Enforced
```

The `status.condition` should display a more relevant message indicating the missing `spec.limi` field, instead of suggesting that the policy is not tied to any route.
