### ISSUE TITLE
Kuadrant requiring IstioOperator even if used for ratelimiting only

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-operator#103]
As far as I know you should be able to use Kuadrant for ratelimiting only even if you do not have access to `IstioOperator`.
CR:
```
apiVersion: kuadrant.kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant-sample
  namespace: kuadrant
spec: {}
status:
  conditions:
    - lastTransitionTime: '2022-11-01T13:34:57Z'
      message: >-
        no matches for kind "IstioOperator" in version
        "install.istio.io/v1alpha1"
      reason: ReconcilliationError
      status: 'False'
      type: Ready
```
