### ISSUE TITLE
Gateway override merge strategy dependant on policy creation order

### ISSUE THREAD

**Issue by martinhesko** [Kuadrant/kuadrant-operator#1052]
During test development, I noticed this only in a case where I had 2 policies targeting the same Gateway, with one providing a merge override.

### Steps to reproduce

Policy 1:
```
spec:
  limits:
    gateway_limit:
      rates:
        - limit: 3
          window: 5s
      when:
        - predicate: request.path == '/anything'
    route_limit:
      rates:
        - limit: 10
          window: 5s
      when:
        - predicate: request.path == '/get'
```

Policy 2:
```
spec:
  overrides:
    limits:
      route_limit:
        rates:
          - limit: 3
            window: 5s
        when:
          - predicate: request.path == '/get'
    strategy: merge
```

- Create policy 1 first targeting the gateway
- Create policy 2 targeting the same Gateway, the policy provides a complete override to Policy 1 instead of Policy 1 staying partially enforced as expected

If Policy 2 is created first it works as expected, with Policy 1 being partially enforced.
