### ISSUE TITLE
Rate limits are not enforced anymore

### ISSUE THREAD

**Issue by averevki** [Kuadrant/kuadrant-operator#1144]
From the `2024-12-17` kuadrant catalogue nightly builds, we see consistent fails in all of our limitador tests inside the [testsuite](https://github.com/Kuadrant/testsuite/tree/main/testsuite/tests/singlecluster/limitador). Every test shows that everything is Accepted and Enforced but requests return 200 when they should be limited.

limitador operator image: `92de465a0cbd325504327229206e7c84c3758891`
limitador image: `8dc09dc62d43ca5dd0e90ca5cb61b2966fdc7faa`
wasm-shim image: `ff60de9d92916c8e2ab91566d314b032b9b062b3`

I see `ERROR limitador_server: Failed reloading limit file: Invalid limit file: Couldn't parse: .[0].conditions: couldn't parse limit.1rp10s__881b2a8e == "1": Error parsing: unrecognized token: '.1' at [0:5]->[0:7] at line 2 column 3` errors during the nightly kuadrant reinstallations, but it's probably unrelated

This is the setup from the [most basic ratelimit test](https://github.com/Kuadrant/testsuite/blob/main/testsuite/tests/singlecluster/limitador/test_basic_limit.py) we have which is failing:

RateLimitPolicy:
```yaml
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: limit-averevki--gbja
  namespace: kuadrant
spec:
  limits:
    basic:
      rates:
        - limit: 2
          window: 15s
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: route-averevki--0xvs
```
<details>
<summary>Gateway</summary>

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw-averevki--pzye
  namespace: kuadrant
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: '*.apps.domain.com'
      name: api
      port: 80
      protocol: HTTP
```
</details>

<details>
<summary>HTTPRoute</summary>

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-averevki--0xvs
  namespace: kuadrant
spec:
  hostnames:
    - hostname-averevki--mla-kuadrant.apps.domain.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gw-averevki--pzye
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: httpbin-averevki--wzyd
          namespace: kuadrant
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
```
</details>
