### ISSUE TITLE
`PlanPolicy` exploration

### ISSUE THREAD

**Issue by alexsnaps** [Kuadrant/kuadrant-operator#1149]
Define a policy that lets the user declare two things: 
 - The plans and their limits
 - The mapping function that maps a user's identity to a said plan

**Comment by adam-cattermole** [comment]
## Scenario

I want to define a plan, that together with a `<Specialized>IdentityPolicy`  (#1148) allows me to map users to a plan, and defines the limits for a plan.

The scenario is defined as follows:
* `bronze`: Any unidentified user (limit: 1000/day)
* `silver`: All identified users (limit: 2000/day)
* `gold`: Identified users with a verified email that ends with `@mydomain.com` (limit: 5000/day)

## PlanPolicy

```yaml
apiVersion: kuadrant.io/v1alpha1
kind: PlanPolicy
metadata:
  name: my-plan
spec:
  targetRef:
    group: kuadrant.io/v1alpha1
    kind: IdentityPolicy
    name: my-auth-ident
  mapping: |
    has(auth.identity) ? (auth.identity.email_verified == "true" && auth.identity.email.endsWith("@mydomain.com") ? "gold" : "silver") : "bronze"
  plans:
    "bronze":
      limits:
        daily: 1000
#        weekly: x
#        monthly: y
#        yearly: z
#        custom:
#          - limit: 1000
#            window: 1d
    "silver":
      limits:
        daily: 2000
    "gold":
      limits:
        daily: 5000
```

## Design Decisions

_The targetRef directly targets the IdentityPolicy rather than a network resource_

* From a users perspective, this is easy to understand that the plans are tied to a particular identification method and targets the same network resources
* That being said there is less fine-grained control over the exact resources this `PlanPolicy` targets
* Are there cases where a `PlanPolicy` does not have any linked `IdentityPolicy`? Or what if `silver` uses one `IdentityPolicy` but `gold` is supposed to use another?

_The plans limits show explicit units rather than expecting the user to configure via `1d`, `1m` etc_

* By looking at the spec it is very clear exactly what this does - a value of 0 infers everything is rate limited, whereas an omitted value infers everything is allowed - for the simple case there is no need to look at documentation
* A `custom: []` field is present where the user can still provide specific limits that map 1:1 with the spec of those in the `RateLimitPolicy`

**Comment by alexsnaps** [comment]
Not sure if this makes the `mapping` function a whole lot more readable, but probably would _if_ the set of plans grows:

```cel
[{
    "gold":auth.identity.email_verified == true && auth.identity.email.endsWith("@mydomain.com"),
    "silver": has(auth.identity),
    "bronze": true,
}].map(m, m.filter(key, m[key]))[0][0]
```

**Comment by adam-cattermole** [comment]
Thanks that makes it a lot clearer - updated the proposal, also thanks for the link, I couldn't find a tool to test  my expression!

> Now I wonder if that mapping function shouldn't, initially at least, "only" take auth.identity as input. It could be the only binding tho... so that if we add more, that'd work too. But could be misleading users in thinking all known attributes are available.

Yep I think that makes sense, but how would we define inputs? a separate field in the yaml or does CEL let us define the parameters?

**Comment by alexsnaps** [comment]
>Yep I think that makes sense, but how would we define inputs? a separate field in the yaml or does CEL let us define the parameters?

I meant to say that _Kuadrant_ only provides what in `auth.identity`, thru "some" _single_ binding for the function to use.

**Comment by Boomatang** [comment]
I have some questions that have being playing on my mind. 

1. How do these `PlanPolices` interact with defaults and overrides? 
2. What resources would get generated? 
3. Is it rateLimitPolices that the operator will manage or is it direct changes to the limitador CR? 
4. How would they fit into the DAG? 
5. Are we expecting user to use both plan policies and policy attachment?

**Comment by alexsnaps** [comment]
`PlanPolicy` is a metapolicy, so it will be translated in "`RateLimitPolicy`" and "`AuthPolicy`" and these will then behave wrt these questions just as before. wrt D&O, I think I'd _not_ support these at this stage, but have them be `Direct` ones

**Comment by guicassolato** [comment]
The `bronze`, `silver` and `gold` plans seem to be relatively strong entities. Their corresponding `limits` are specified in a quite declarative way under `plans`. The `mapping` piece however looks more like a function that could yield almost anything, structured in almost anyway. I wonder why we wouldn't want to be stricter about that and perhaps have instead sth like:

```yaml
apiVersion: kuadrant.io/v1alpha1
kind: PlanPolicy
metadata:
  name: my-plan
spec:
  targetRef:
    group: kuadrant.io/v1alpha1
    kind: IdentityPolicy
    name: my-auth-ident
  plans:
    "bronze":
      limits:
        daily: 1000
#        weekly: x
#        monthly: y
#        yearly: z
#        custom:
#          - limit: 1000
#            window: 1d
      identitites: true
    "silver":
      limits:
        daily: 2000
      identitites: has(auth.identity)
    "gold":
      limits:
        daily: 5000
      identitites: has(auth.identity) && auth.identity.email_verified && auth.identity.email.endsWith("@mydomain.com")
```

**Comment by thomasmaas** [comment]
Or even take it one step further:

```yaml
  plans:
    "bronze":
      limits:
        daily: 1000
      identitites: "group_1"
    "silver":
      limits:
        daily: 2000
      identitites: "group_2"
    "gold":
      limits:
        daily: 5000
      identitites: "group_3"
```

and the identity policy would have something like

```yaml
  identies:
    "group_1":
        auth.identity: false
    "group_2":
        auth.identity: true        
    "group_3":
        auth.identity: true
        auth.identity.email_verified: true 
        auth.identity.email.endsWith: "@mydomain.com"
```

Don't take this literally, just exploring ideas. Finding the right level of abstraction for meta policies is very important to make them valuable. Having to write CEL in a meta policy makes me feel the policy is not specific enough? Better have many meta policies, each of them being very precise, limited in scope and super focussed?

**Comment by adam-cattermole** [comment]
I think that I originally had a very similar approach to both of these with regard to the specificity within the plans but I think that the only concern is that there's an implicit ordering to the plans, where we assume that the most restrictive match wins? for example in your case @guicassolato what do we use to determine that the `identities` for `"gold"` takes precedence over `"silver"` (or `"bronze"` for that matter), is it just that it's the last one in the list?

**Comment by alexsnaps** [comment]
If you all think that's the way to go, then sure... but as I tried to explain in the community call, please be mindful that moving (and as such repeating) the "predicate" (`identities`) to each plan means that multiple can apply and now needs to be resolved in a way or another than is then _implicit_.

>The `mapping` piece however looks more like a function that could yield almost anything
No, it's not, it has to evaluate to a `string` (which can be determined in many cases) that needs to be the name of the plan... that last bit is a little harder to validate upfront. Tho this is the same problem as "what if a CEL expression" errs out...

**Comment by thomasmaas** [comment]
Some thoughts:
- Shouldn't figuring out which identity applies be the responsibility of the identity policy? 
- I'm aware that these meta policies need to be auto converted into auth and rl policies that will do the actual work but I think we should ignore that fact at this moment and design this outside in (API first), not inside out. And we should constantly ask ourselves: is this actually more approachable/easier to grasp for a casual user?
- Don't we think you should be able to switch from one identity system to another without having to touch your plans policy? The moment we start adding things like `email.verified` in the plans policy that will be hard. By having the plans policy only talk about plans and an identity concept like "group" that is defined elsewhere (in an identity policy) you have a clear separation of concerns.
- I can imagine that we have specific identity policies for specific identity flows/tools. Like a Keycloak identity policy that lets your work with groups in Keycloak. And as such the keycloak identity policy will look different from the one you use to connect with Gitlab, which I think the current example is based on. 
- One of the plans could be "internal" and use a different identity system all-together.

**Comment by maleck13** [comment]
> The `bronze`, `silver` and `gold` plans seem to be relatively strong entities. Their corresponding `limits` are specified in a quite declarative way under `plans`. The `mapping` piece however looks more like a function that could yield almost anything, structured in almost anyway. I wonder why we wouldn't want to be stricter about that and perhaps have instead sth like:
> 
> apiVersion: kuadrant.io/v1alpha1
> kind: PlanPolicy
> metadata:
>   name: my-plan
> spec:
>   targetRef:
>     group: kuadrant.io/v1alpha1
>     kind: IdentityPolicy
>     name: my-auth-ident
>   plans:
>     "bronze":
>       limits:
>         daily: 1000
>       identitites: true
>     "silver":
>       limits:
>         daily: 2000
>       identitites: has(auth.identity)
>     "gold":
>       limits:
>         daily: 5000
>       identitites: has(auth.identity) && auth.identity.email_verified && auth.identity.email.endsWith("@mydomain.com")

I found this quite readable vs the original. On plan selection, it may be reasonable to use a list as @guicassolato says with a clearly documented rule on how selection is made in the case of multiple matches. For example we always pick the first match in the list of options, so ensure to define your plans from most restrictive on selection criteria to the least restrictive. So if I wanted to add a `platinum` I could add a new plan to the top of the list that has  : 

```
 "platinum":
      limits:
         daily: 15000
       identitites: has(auth.identity) && auth.identity.email_verified && auth.identity.group.equals("platinum")
````
