### ISSUE TITLE
Add e2e tests for mTLS Configuration via Kuadrant CR

### ISSUE THREAD

**Issue by emmaaroche** [Kuadrant/kuadrant-operator#1230]
**Description:**

Create end-to-end tests in the [Kuadrant/testsuite](https://github.com/Kuadrant/testsuite) repository to validate the correct behavior of the system when the mTLS configuration is toggled in the Kuadrant CR.

**Test Cases:**

1\. **Envoy Sidecar Container Labels**

- **When `mtls` is enabled:**
  Verify that the `limitador` and `authorino` deployment include the Envoy sidecar container label `sidecar.istio.io/inject: "true"` in `spec.template.metadata.labels`.

- **When `mtls` is disabled:**
  Verify that the Envoy sidecar container label `sidecar.istio.io/inject` is removed from `spec.template.metadata.labels` in both the `limitador` and `authorino` deployments.

2\. **EnvoyFilter TLS Context**

- **When `mtls` is enabled:**
  Verify that each `EnvoyFilter` resource with a name starting with `kuadrant-` in the gateway namespace includes the following TLS context configuration under `spec.configPatches[].patch.value`:

```yaml
transport_socket:
  name: envoy.transport_sockets.tls
  typed_config:
    '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
    common_tls_context:
      tls_certificate_sds_secret_configs:
      - name: default
        sds_config:
          api_config_source:
            api_type: GRPC
            grpc_services:
            - envoy_grpc:
                cluster_name: sds-grpc
      validation_context_sds_secret_config:
        name: ROOTCA
        sds_config:
          api_config_source:
            api_type: GRPC
            grpc_services:
            - envoy_grpc:
                cluster_name: sds-grpc
```

- **When `mtls` is disabled:**
  Verify that the TLS context is removed from each of the affected `EnvoyFilter` resources.

3\. **PeerAuthentication Resource**

- **When `mtls` is enabled:**
  Verify that a `PeerAuthentication` resource named `default` exists in the `kuadrant-system` namespace with:

```yaml
spec:
  mtls:
    mode: STRICT
```

- **When `mtls` is disabled:**
  Verify that no `PeerAuthentication` resource named `default` exists in the `kuadrant-system` namespace.
