### ISSUE TITLE
WASMShim version is not locked

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-operator#128]
We use the Kuadrant operator from OperatorHub, and while both `Limitador` and `Authorino` seem to have locked image versions, the WASMShim uses the latest image. WASMPlugin that was created, notice the image:
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: kuadrant-istio-ingressgateway
  namespace: istio-system
spec:
  phase: STATS
  pluginConfig:
    failure_mode_deny: true
    rate_limit_policies:
      - gateway_actions:
          - configurations: []
        hostnames:
          - '*'
        name: '*'
        rate_limit_domain: 'istio-system/istio-ingressgateway#*'
        upstream_cluster: kuadrant-rate-limiting-service
  selector:
    matchLabels:
      istio: ingressgateway
  url: 'oci://quay.io/kuadrant/wasm-shim:latest'
```
