### ISSUE TITLE
Rate limiting Gateway object doesn't work

### ISSUE THREAD

**Issue by jsmolar** [Kuadrant/kuadrant-operator#129]
Rate limit has no effect when applied to Gateway object (environment is set according to hands-on guide). When similar `RateLimitPolicy` cr is applied to `HTTPRoute` (as stated in the guide), it works as expected.

`RateLimitPolicy` cr:
```
kubectl -n toystore apply -f -<<EOF
---
apiVersion: kuadrant.io/v1beta1
kind: RateLimitPolicy
metadata:
  name: istio-ingressgateway
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: istio-ingressgateway
  rateLimits:
  - configurations: []
    limits:
      - conditions: []
        maxValue: 2
        seconds: 10
        variables: []
EOF
```

This status can be observed in `RateLimitPolicy` object:
```
conditions:
    - lastTransitionTime: '2023-01-05T17:04:04Z'
      message: HTTPRoute is ratelimited
      reason: HTTPRouteProtected
      status: 'True'
      type: Available
```

**Comment by pehala** [comment]
WASMPlugin generated for looks like this:
```
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: kuadrant-istio-ingressgateway
  namespace: istio-system
spec:
  phase: STATS
  pluginConfig:
    failure_mode_deny: true
    rate_limit_policies:
      - gateway_actions:
          - configurations: []
        hostnames:
          - '*'
        name: '*'
        rate_limit_domain: 'istio-system/istio-ingressgateway#*'
        upstream_cluster: kuadrant-rate-limiting-service
  selector:
    matchLabels:
      istio: ingressgateway
  url: 'oci://quay.io/kuadrant/wasm-shim:latest'
```
Gateway:
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  annotations:
    kuadrant.io/namespace: kuadrant
    kuadrant.io/ratelimitpolicies: '[{"Namespace":"istio-system","Name":"gw-limit"}]'
    kuadrant.io/ratelimitpolicy-direct-backref: istio-system/gw-limit
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"gateway.networking.k8s.io/v1alpha2","kind":"Gateway","metadata":{"annotations":{},"labels":{"istio":"ingressgateway"},"name":"istio-ingressgateway","namespace":"istio-system"},"spec":{"addresses":[{"type":"Hostname","value":"istio-ingressgateway.istio-system.svc.cluster.local"}],"gatewayClassName":"istio","listeners":[{"allowedRoutes":{"namespaces":{"from":"All"}},"name":"default","port":80,"protocol":"HTTP"}]}}
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    istio: ingressgateway
spec:
  addresses:
    - type: Hostname
      value: istio-ingressgateway.istio-system.svc.cluster.local
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: default
      port: 80
      protocol: HTTP
```
I also found out that if I manually update the WasmPlugin to include Rules in its configuration, it starts working at least for the paths and host I specified:
```
spec:
  phase: STATS
  pluginConfig:
    failure_mode_deny: true
    rate_limit_policies:
      - gateway_actions:
          - configurations:
            - rules:
              - hosts:
                  - '*.toystore.apps.ocp-wide.osp.api-qe.eng.rdu2.redhat.com'
                methods:
                  - GET
                paths:
                  - /toy*
        hostnames:
          - '*'
        name: '*'
        rate_limit_domain: 'istio-system/istio-ingressgateway#*'
        upstream_cluster: kuadrant-rate-limiting-service
```

**Comment by eguzki** [comment]
This is interesting, though. 

People will expect to have this kind of config for unconditional rate limiting. 
```yaml
 rateLimits:
  - configurations: []
    limits:
      - conditions: []
        maxValue: 2
        seconds: 10
        variables: []
```
Maybe we should add some constraint that `configurations` should not be empty list.
