### ISSUE TITLE
# UnSet topologySpreadConstraints (authorino deployment)

### ISSUE THREAD

**Issue by Boomatang** [Kuadrant/kuadrant-operator#1301]
## What
When the `spec.resilience.authorization` feature is disabled in the kuadrant CR, the kuadrant-operator should remove any configuration changes it did for topology spread constraints.

## Why
The operator should be predictable in how it manages resources, and undo any changes it may have done when the `spec.resilience.authorization` feature is disabled.

## How
From the authorino deployment remove the entries using the following keys.
- `topologyKey: kubernetes.io/hostname`
- `topologyKey: kubernetes.io/zone`
The authorino deployment should be in the kuadrant topology (state of the world)

## Done
- [ ] When the `spec.resilience.authorization` feature is disabled in the kuadrant CR the following configuration is removed from the authorino deployment
```yaml
spec:
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              authorino-resource: authorino
        - maxSkew: 1
          topologyKey: kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              authorino-resource: authorino
```
- [ ] If there is user defined constraints in the `spec.template.spec.topologySpreadConstraints` only the entries created by the kuadrant-operator are removed.
