### ISSUE TITLE
# Set topologySpreadConstraints (limitador deployment)

### ISSUE THREAD

**Issue by Boomatang** [Kuadrant/kuadrant-operator#1314]
## What
Add the [Pod Topology Spread Constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) to the limitador deployment configuration when the `spec.resilience.authorization` feature is enabled in the kuadrant CR.

## Why
To be more resilient the deployment need to react to network failures. 
The Pod Topology Spread Constraints allows us to do that.

## How
Update the limitador deployment with the following configuration.
```yaml
spec:
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              limitador-resource: limitador
        - maxSkew: 1
          topologyKey: kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              limitador-resource: limitador
```

## Done
- [ ] When the `spec.resilience.authorization` feature is enabled the following configuration should be in the limitador deployment.
```yaml
kind: Deployment
metadata:
  name: limitador
spec:
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              limitador-resource: limitador
        - maxSkew: 1
          topologyKey: kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              limitador-resource: limitador
```
