### ISSUE TITLE
Deleted RLP are not removed from Limitador

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-operator#132]
Similar to #126 I see undeleted limits in Limitador resource. I believe those happened when we deleted Gateway first and RLP second, but I am not 100% sure yet:
```
apiVersion: limitador.kuadrant.io/v1alpha1
kind: Limitador
metadata:
  name: limitador
  namespace: kuadrant
spec:
  limits:
    - conditions:
        - userID == bob
      max_value: 2
      namespace: >-
        jsmolar-gw/istio-ingressgateway#*.toystore.apps.ocp-wide.osp.api-qe.eng.rdu2.redhat.com
      seconds: 10
      variables: []
    - conditions:
        - userID == alice
      max_value: 5
      namespace: >-
        jsmolar-gw/istio-ingressgateway#*.toystore.apps.ocp-wide.osp.api-qe.eng.rdu2.redhat.com
      seconds: 10
      variables: []
    - conditions: []
      max_value: 2
      namespace: 'istio-system/istio-ingressgateway#*'
      seconds: 10
      variables: []
```
Only policy on the server:
```
apiVersion: kuadrant.io/v1beta1
kind: RateLimitPolicy
metadata:
  annotations:
    kuadrant.io/namespace: kuadrant
  name: gw-limit
  namespace: istio-system
  finalizers:
    - ratelimitpolicy.kuadrant.io/finalizer
spec:
  rateLimits:
    - configurations:
        - actions:
            - generic_key:
                descriptor_key: limited
                descriptor_value: '1'
      limits:
        - conditions: []
          maxValue: 2
          seconds: 10
          variables: []
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: istio-ingressgateway
```
