### ISSUE TITLE
Improvements to RateLimitPolicy

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-operator#133]
Currently, the minimal working example (At least what I could do) looks like this. However, this could be much easier for the simple limit I want to enforce.
```
apiVersion: kuadrant.io/v1beta1
kind: RateLimitPolicy
metadata:
  name: gw-limit
  namespace: istio-system
spec:
  rateLimits:
    - configurations:
        - actions:
            - generic_key:
                descriptor_key: limited
                descriptor_value: '1'
      limits:
        - conditions: []
          maxValue: 5
          seconds: 10
          variables: []
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: istio-ingressgateway
```
Notable problems:

* `configurations` cannot be empty or the rate limit won't work, and it is not always needed
   * **Solution 1**: If it is empty, Kuadrant could generate a static action key.
   * **Solution 2**: Make Kuadrant throw an error if it is empty.
* `conditions` and `variables` are not required but need to be specified at least as an empty list:
   * **Solution**: Make them optional and if missing, assign an empty list. 

Please let me know what you think. These are just what I see as problems from my perspective.
