### ISSUE TITLE
RateLimitPolicy conditions don't indicate that the limit is applied

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-operator#140]
`RateLimitPolicy` has a condition that says that `HTTPRoute is protected`; however, that condition doesn't mean that the RLP is being applied and you can start making requests. You need to wait an additional minute or so for the limit to be applied.

**Comment by thomasmaas** [comment]
Do you mean "state" when you say "condition"? And if so, is there a way to make that state reflect reality?

**Comment by pehala** [comment]
The RLP has this condition and even when the status is "True" and the messages says that `HTTPRoute is ratelimited`, the limit is not applied yet and you need to wait a minute or so for it to work. 
```
status:
  conditions:
    - lastTransitionTime: '2023-01-16T11:50:19Z'
      message: HTTPRoute is ratelimited
      reason: HTTPRouteProtected
      status: 'True'
      type: Available
```
