### ISSUE TITLE
Update to remove the need to install istio via the istio operator 

### ISSUE THREAD

**Issue by R-Lawton** [Kuadrant/kuadrant-operator#168]
Currently to be able to avail of the rate limit and auth policy in Kuadrant you need to have an istio operator cr. To be able to have an istio operator cr you have to install istio operator which is now discouraged by the istio team.  Istioctl and Helm installation methods are recommended [instead](https://istio.io/latest/docs/setup/install/operator/).

**Comment by pehala** [comment]
> Personally, I don’t think that’s the direction we should be going, and neither should Istio IMHO.

While I agree, Istio is already going that way as IstioOperator will not have new features and is discouraged (https://istio.io/latest/docs/setup/install/operator/)

**Comment by maleck13** [comment]
When you use the istioctl or helm approach, is there no configuration resource created that kuadrant could hook into if it was told where that resource was? I guess my question is where is the config stored if not when not in the operator resource?

**Comment by guicassolato** [comment]
@maleck13 

There is a ConfigMap that by default looks like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: istio-system
  name: istio
  labels:
    install.operator.istio.io/owning-resource: istiocontrolplane
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: default
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.13.2
    release: istio
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
```

The ConfgiMap can be patched in the following way to inject the extension provider info:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: istio-system
  name: istio
  labels: […]
data:
  mesh: |-
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata: {}
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
    enablePrometheusMerge: true
    extensionProviders:
    - envoyExtAuthzGrpc:
        port: 50051
        service: authorino-authorino-authorization.kuadrant-system.svc.cluster.local
      name: kuadrant-authorization
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'
```

The change is not reconciled back to the IstioOperator custom resource that Istio will store in the cluster regardless. So we'd need to reflect the change there as well.

We may also need our operator to have permissions to redeploy Istio, as I'm not sure if the changes to the ConfigMap will take effect otherwise.

**Comment by guicassolato** [comment]
Ok. Redeploying Istio might not be needed in the end, which BTW is consistent with the instructions [here](https://istio.io/latest/docs/tasks/security/authorization/authz-custom/).

I've tested locally with the following steps from the Kuadrant Operator repo (even though not really using Kuadrant here):

❶ Create a cluster with Gateway API and Istio:

```sh
make kind-create-cluster gateway-api-install istioctl
./bin/istioctl install -f config/dependencies/istio/istio-operator.yaml
make deploy-gateway
```

❷ Deploy a sample API:

```sh
kubectl apply -f https://raw.githubusercontent.com/kuadrant/authorino-examples/main/talker-api/talker-api-deploy.yaml
```

```sh
kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: talker-api
spec:
  parentRefs:
  - name: istio-ingressgateway
    namespace: istio-system
  hostnames:
  - talker-api.local
  rules:
  - backendRefs:
    - name: talker-api
      port: 3000
EOF
```

❸ Deploy Authorino (without Kuadrant):

```sh
kubectl apply -f https://raw.githubusercontent.com/Kuadrant/authorino-operator/main/config/deploy/manifests.yaml
```

```sh
kubectl apply -f -<<EOF
apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
spec:
  listener:
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
EOF
```

❹ Edit the mesh config:

```sh
kubectl edit configmap istio -n istio-system
```

Add the following bit to the `defaultConfig`:

```yaml
extensionProviders:
- name: authorino
  envoyExtAuthzGrpc:
    port: 50051
    service: authorino-authorino-authorization.default.svc.cluster.local
```

❺ Wire ext-authz up in the gateway for the sample API:

```sh
kubectl apply -n istio-system -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: talker-api-ext-authz
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: authorino
  rules:
  - to:
    - operation:
        hosts: ["talker-api.local"] 
        paths: ["/secure*"]
EOF
```

❻ Send requests:

```sh
kubectl port-forward service/istio-ingressgateway 8000:80 -n istio-system 2>&1 >/dev/null &
```

```sh
curl -H "Host: talker-api.local" http://localhost:8000/secure -i
# HTTP/1.1 404 Not Found
# x-ext-auth-reason: Service not found  <=== It means the request hit Authorino
```
