### ISSUE TITLE
Kuadrant resource stuck deleting

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-operator#169]
I encountered an issue where my Kuadrant resource is waiting for deletion due to the finalizer. At the time of creation I did not have `istiocontrolplane` installed (as can be seen in the status section), and after I created it, it didn't get updated and when I tried to delete it got stuck.

The resolution was to restart `kuadrant-operator` pod.

```
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  deletionTimestamp: '2023-04-18T10:47:42Z'
  name: kuadrant-sample
  namespace: kuadrant
  finalizers:
    - kuadrant.io/finalizer
spec: {}
status:
  conditions:
    - lastTransitionTime: '2023-04-18T08:27:22Z'
      message: IstioOperator.install.istio.io "istiocontrolplane" not found
      reason: ReconcilliationError
      status: 'False'
      type: Ready
  observedGeneration: 1
```

This is probably a race condition and is not a major issue, but I am creating the issue for future or if someones encounters it as well
