### ISSUE TITLE
Support a limit strategy in rate limit policy

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#271]
**UseCase**

I am using shared storage between multiple gateways instances and I want to decide if the limits set by my policy should shared or unique 

What does shared vs unique mean?

The expectation is that there is shared storage in place that 2 or more instances of limitador are connected to. As a user I want to declare  wether I want the counters behind those limits to be shared or unique based on my requirements. For example creating a global or infra limit

**Possible Solution**

Add a property to the spec of RLP to inidicate if a limit is unique or shared

```
  rates:
      - limit: 100
        duration: 1
        unit: second
        strategy: unique # default is shared
```

I am not familar with how we construct the counter name currently, but I imagine we could prefix it in the unique case with some form of guid
