### ISSUE TITLE
Operator crash loops on RLP targetting HTTPRoute with no namespace in parentRef

### ISSUE THREAD

**Issue by adam-cattermole** [Kuadrant/kuadrant-operator#333]
I was testing deploying a RLP in a cluster where I have an HTTPRoute targetting a gateway without the namespace set explicitly. The operator crash loops on this line because we deref a nil pointer https://github.com/Kuadrant/kuadrant-operator/blob/main/pkg/common/gatewayapi_utils.go#L221 as the `parentRef.Namespace` is nil.

Gateway:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: toystore-gateway
  namespace: kuadrant-system
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: http
      port: 80
      protocol: HTTP
```

HTTPRoute:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: toystore
  namespace: kuadrant-system
spec:
  hostnames:
    - api.toystore.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: toystore-gateway
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: toystore
          port: 80
          weight: 1
      matches:
        - method: GET
          path:
            type: PathPrefix
            value: /cars
        - method: GET
          path:
            type: PathPrefix
            value: /dolls
    - backendRefs:
        - group: ''
          kind: Service
          name: toystore
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /admin
```

RLP:
```yaml
apiVersion: kuadrant.io/v1beta2
kind: RateLimitPolicy
metadata:
  namespace: kuadrant-system
  finalizers:
    - ratelimitpolicy.kuadrant.io/finalizer
spec:
  limits:
    create-toy:
      rates:
        - duration: 10
          limit: 5
          unit: second
      routeSelectors:
        - matches:
            - method: GET
              path:
                type: Exact
                value: /cars
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: toystore
```
