### ISSUE TITLE
Authpolicy status should not report error when authconfig resource is not required.

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/kuadrant-operator#349]
Given the following topology:

```
Gateway prod-web

HTTPRoute petstore-route   ->  gateway prod-web

AuthPolicy gw-auth -> Gateway prod-web

Authpolicy petstore-route -> HTTPRoute petstore-route
```

The status field of the `gw-auth` policy reports as "Not Available"

```yaml
 status:                                           
  conditions:                                     
  - lastTransitionTime: "2023-11-30T15:40:34Z"    
    message: AuthScheme is not ready yet          
    reason: AuthSchemeNotReady                    
    status: "False"                               
    type: Available                               
  observedGeneration: 2                           
```

This is wrong because the `gw-auth` policy does not need an AuthConfig resource as there is no "free" HTTPRoutes.  It should report as "Available" instead.
