### ISSUE TITLE
DNSPolicy: defaultGeo should be required in the DNSPolicy spec  

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/kuadrant-operator#554]
**What**

The `defaultGeo` value in `spec.loadBalancing.geo` should be required, and it should not be possible to create a geo section without providing it with a non zero length string.

Invalid:
```
spec:
  loadBalancing:
    geo: {}
  routingStrategy: loadbalanced
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: distributed-us
```

It should also handle better the case where the geo for whatever reason is calculated to be an empty string. Currently it will create invalid dnsNames like `.klb.distributed.managed.hcpapps.net` where it should be `<geocode>.klb.distributed.managed.hcpapps.net`.
