### ISSUE TITLE
GW RLP status not updated when Route RLP is deleted

### ISSUE THREAD

**Issue by KevFan** [Kuadrant/kuadrant-operator#587]
# Description
With a GW RLP defining defaults and a Route RLP, when the Route RLP is deleted, the status of the GW RLP is not updated to indicate that is it now enforced. 

The following GW RLP status condition is kept:
```yaml
conditions:
  - lastTransitionTime: "2024-04-29T10:32:00Z"
    message: RateLimitPolicy has been accepted
    reason: Accepted
    status: "True"
    type: Accepted
  - lastTransitionTime: "2024-04-29T10:36:12Z"
    message: RateLimitPolicy is overridden by [default/toystore]
    reason: Overridden
    status: "False"
    type: Enforced
```
There is a bug for not updating the affected GW RLP status when Route RLPs are deleted
