### ISSUE TITLE
DNSPolicy Enforced condition is not updated

### ISSUE THREAD

**Issue by ficap** [Kuadrant/kuadrant-operator#611]
When there is error in dnsrecord of dnspolicy, Enforced status is not updated to Enforced=false in dnspolicy's status. the status looks like this:
```
      conditions:
        - lastTransitionTime: '2024-05-03T10:37:03Z'
          message: DNSPolicy has been accepted
          reason: Accepted
          status: 'True'
          type: Accepted
        - lastTransitionTime: '2024-05-03T10:37:03Z'
          message: DNSPolicy has been successfully enforced
          reason: Enforced
          status: 'True'
          type: Enforced
      observedGeneration: 1
      recordConditions:
        backend.ficap.example.com:
          - lastTransitionTime: '2024-05-03T10:52:12Z'
            message: 'The DNS provider failed to ensure the record: failed to submit
              all changes for the following zones: [/hostedzone/ZONEID]'
            observedGeneration: 1
            reason: ProviderError
            status: 'False'
            type: Ready
```
Depending on the meaning of enforced condition it should be updated properly.
