### ISSUE TITLE
Add `allowedRoutes.namespaces` to Gateways table in platform engineer dashboard view

### ISSUE THREAD

**Issue by david-martin** [Kuadrant/kuadrant-operator#667]
Checking with @maleck13 on this feedback item, but I think it might be `allowedRoutes.namespaces` from https://gateway-api.sigs.k8s.io/concepts/api-overview/?h=allowedroutes#restricting-route-attachment

e.g.

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: prod-web
spec:
  gatewayClassName: example
  listeners:
  - protocol: HTTP
    port: 80
    name: prod-web-gw
    allowedRoutes:
      namespaces:
        from: Same
```
