### ISSUE TITLE
Support OpenShift Service Mesh

### ISSUE THREAD

**Issue by pehala** [Kuadrant/kuadrant-operator#68]
OpenShift Service Mesh is Red Hat's downstream product of Istio. The most relevant difference compared to an upstream Istio is that it doesn't use `IstioOperator` but instead defines their own resources, notably `ServiceMeshControlPlane` which deploys the mesh and `ServiceMeshMember`/`ServiceMeshMemberRoll` which handle which namespaces are part of the mesh.

This means:
* Kuadrant cannot interact with it as the `IstioOperator` resource is missing (#103)
* I am not sure if it makes sense to bind Kuadrant to `ServiceMeshControlPlane` as the mesh and gateways can be spread across multiple namespaces

- [x] #69 
- [x] #102
- [x] #110 
- [x] #104 
- [x] #106 
- [x] #105
- [x] #103

**Comment by eguzki** [comment]
I was able to run Kuadrant RateLimitPolicy to protect a service in the service mesh. Here steps needed and findings.

## Requirements
* The backend service has to be added to the service mesh. Otherwise OSSM does not honor Gateway API HTTPRoutes.

## Kuadrant adaptation
Kuadrant version: [OSSM](https://github.com/Kuadrant/kuadrant-operator/tree/OSSM) branch. As of today, the differences from the `main` branch are the following:
* **AuthPolicies disabled** 
 PRs: 
  *  #104
  *  #106 
  *  #110

Authorization protection using AuthPolicies is disabled. Eventhough the CRDs are available and the controller is watching for AuthPolicy objects, authorino is not deployed and the service mesh does not have any external authorization service registered. 

* **OLM installation fixed** 
 PRs: 
  *  #105


## User Guide
I would name this guide as: *Rate Limiting your services running in OSSM with Kuadrant's RateLimitPolicy*

* Install OSSM 2.3 required Operators

OSSM 2.3 installation guide: https://docs.openshift.com/container-platform/4.11/service_mesh/v2x/installing-ossm.html

This step is about the operators. The ServiceMeshControlPlane object will be installed later.

* Install Gateway API
Currently using Group/Version `gateway.networking.k8s.io/v1alpha2`. [OSSM's official doc about Gateway API support](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.11/html/service_mesh/service-mesh-2-x#kubernetes-gateway-api)

```
kubectl get crd gateways.gateway.networking.k8s.io || { kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.4.0" | kubectl apply -f -; }
```

* Deploy Service Mesh control plane instance with Gateway API enabled
```yaml
---
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  runtime:
    components:
      pilot:
        container:
          env:
            PILOT_ENABLE_GATEWAY_API: "true"
            PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER: "true"
            PILOT_ENABLE_GATEWAY_API_STATUS: "true"
  version: v2.3
  policy:
    type: Istiod
  tracing:
    type: Jaeger
    sampling: 10000
  telemetry:
    type: Istiod
  addons:
    prometheus:
      enabled: true
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
```
