### ISSUE TITLE
Set Enforced to false when DNSPolicy does not succeed for all listener

### ISSUE THREAD

**Issue by ficap** [Kuadrant/kuadrant-operator#685]
When a DNSPolicy is attached to a Gateway with a single listener and corresponding HTTPRoute is created, DNSRecord for the only listener fails like in the example. In this case when DNSPolicy fails for all listeners the condition should be `Enforced: false`. Now it is `Enforced: true` with message that the policy is partially enforced which it is not.

```
status:
  conditions:
    - lastTransitionTime: '2024-06-03T12:21:42Z'
      message: DNSPolicy has been accepted
      reason: Accepted
      status: 'True'
      type: Accepted
    - lastTransitionTime: '2024-06-03T12:21:42Z'
      message: DNSPolicy has been partially enforced
      reason: Enforced
      status: 'True'
      type: Enforced
  observedGeneration: 1
  recordConditions:
    '*.tju51nm88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888.example.com':
      - lastTransitionTime: '2024-06-03T12:21:42Z'
        message: 'The DNS provider failed to ensure the record: Failure in zone example.com. [Id: /hostedzone/ZONEID] when submitting change: InvalidChangeBatch: FATAL problem: DomainLabelTooLong (Domain label is too long) encountered with ''tju51nm888888888888888888888888888888888888888888888888888888888'''
        observedGeneration: 1
        reason: ProviderError
        status: 'False'
        type: Ready
```
