### ISSUE TITLE
AuthPolicy does not recover from error state automatically if root cause of the error got fixed

### ISSUE THREAD

**Issue by trepel** [Kuadrant/kuadrant-operator#702]
### Overview

If AuthPolicy gets into "AuthPolicy has encountered some issues: AuthScheme is not ready yet" error state (Accepted=True, Enforced=False) then it is not automatically reconciled to Enforced=True by Kuadrant operator even if the root cause of the error is gone. One has to trigger the reconciliation manually e.g. by updating the AuthPolicy CR.

### Steps to reproduce

Basically follow the scenario for identical hostnames: https://github.com/Kuadrant/kuadrant-operator/blob/main/doc/auth.md#limitation-multiple-network-resources-with-identical-hostnames
In short:
- create two HTTPRoutes declaring identical hostnames
- create a 1st AuthPolicy attached to one of the HTTPRoutes
- create a 2nd AuthPolicy attached to the other HTTPRoute
- this 2nd AuthPolicy should end up with "AuthScheme is not ready yet" error
- delete the 1st AuthPolicy
- observe that 2nd AuthPolicy never gets onto Enforced=True state
- change the 2nd AuthPolicy (add some authorization rule, or response success header etc)
- once saved the 2nd AuthPolicy is immediately successfully enforced

Example how to change the AuthPolicy CR:
```
spec:
  rules:
    response:
      success:
        headers:
          dummy:
            metrics: false
            plain: {}
            priority: 0
```
