### ISSUE TITLE
Adding Ratelimiting to the same gateway causes multiple requests to Limitador

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#73]
If you add two APIProducts with authenticated rate limiting a request to 1 endpoint will trigger 2 requests to limitador. 1 for each rate limit filter added at the gateway level. The number of requests will grow proportional to the number of filters added.

**Steps**

- create two echo apis
- label them with the discovery label
- add two api products

```
apiVersion: networking.kuadrant.io/v1beta1
kind: APIProduct
metadata:
  name: bookstore
  namespace: default
spec:
  hosts:
    - bookstore.127.0.0.1.nip.io
  APIs:
    - name: bookstore
      namespace: default
  securityScheme:
    - name: MyAPIKey
      apiKeyAuth:
        location: authorization_header
        name: APIKEY
        credential_source:
          labelSelectors:
            secret.kuadrant.io/managed-by: authorino
            api: toystore
  rateLimit:
    authenticated:
      maxValue: 3
      period: 5


apiVersion: networking.kuadrant.io/v1beta1
kind: APIProduct
metadata:
  name: toystore
  namespace: default
spec:
  hosts:
    - toystore.127.0.0.1.nip.io
  APIs:
    - name: toystore
      namespace: default
  securityScheme:
    - name: MyAPIKey
      apiKeyAuth:
        location: authorization_header
        name: APIKEY
        credential_source:
          labelSelectors:
            secret.kuadrant.io/managed-by: authorino
            api: toystore
  rateLimit:
    authenticated:
      maxValue: 1
      period: 5

```

make a single request to the bookstore in the limitador logs you will see it is called for both domains:

``` 
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Settings { flags: (0x0), initial_window_size: 1048576, max_frame_size: 16384 }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::proto::connection] Connection; peer=Server
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Settings { flags: (0x0), header_table_size: 4096, enable_push: 0, max_concurrent_streams: 2147483647, initial_window_size: 268435456 }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Settings { flags: (0x1: ACK) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 268369921 }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Settings { flags: (0x1: ACK) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::proto::settings] received settings ACK; applying Settings { flags: (0x0), initial_window_size: 1048576, max_frame_size: 16384 }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 983041 }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG limitador_server::envoy_rls::server] Request received: Request { metadata: MetadataMap { headers: {"te": "trailers", "grpc-timeout": "20m", "content-type": "application/grpc", "x-b3-traceid": "2fe576109219495397a1b57aaa15c5ff", "x-b3-spanid": "2c2b33a7d145a8b1", "x-b3-parentspanid": "97a1b57aaa15c5ff", "x-b3-sampled": "0", "x-envoy-internal": "true", "x-forwarded-for": "10.244.0.8", "x-envoy-expected-rq-timeout-ms": "20"} }, message: RateLimitRequest { domain: "bookstore.default", descriptors: [RateLimitDescriptor { entries: [Entry { key: "user_id", value: "alice" }] }], hits_addend: 0 }, extensions: Extensions }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Data { stream_id: StreamId(1) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Headers { stream_id: StreamId(3), flags: (0x4: END_HEADERS) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_read] received frame=Data { stream_id: StreamId(3), flags: (0x1: END_STREAM) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG limitador_server::envoy_rls::server] Request received: Request { metadata: MetadataMap { headers: {"te": "trailers", "grpc-timeout": "20m", "content-type": "application/grpc", "x-b3-traceid": "2fe576109219495397a1b57aaa15c5ff", "x-b3-spanid": "b5cf1278e05acd55", "x-b3-parentspanid": "97a1b57aaa15c5ff", "x-b3-sampled": "0", "x-envoy-internal": "true", "x-forwarded-for": "10.244.0.8", "x-envoy-expected-rq-timeout-ms": "20"} }, message: RateLimitRequest { domain: "toystore.default", descriptors: [RateLimitDescriptor { entries: [Entry { key: "user_id", value: "alice" }] }], hits_addend: 0 }, extensions: Extensions }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(3), flags: (0x4: END_HEADERS) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Data { stream_id: StreamId(3) }
limitador-7f7c645979-92xfm limitador [2021-12-23T11:07:53Z DEBUG h2::codec::framed_write] send frame=Headers { stream_id: StreamId(3), flags: (0x5: END_HEADERS | END_STREAM) }

```
