### ISSUE TITLE
[state-of-the-world] common policy status controller

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/kuadrant-operator#730]
When dependent CRDs do not exist, some controllers are disabled. Currently controller-runtime panics when a controller watches a not existing type. When the controllers are disabled, they cannot report on the status of the policies. The only "error message" would be available in the operator logs. 

This controller would update the status of the policies with understandable message when dependent types (CRDs) are not available. Some uses cases:
* TLSPolicy → depends on the cert-manager CRDs (this [PR](https://github.com/Kuadrant/kuadrant-operator/pull/715) adds watchers on cert-manager types) 
* RLP, auth, tls, dns policies → when GatewayAPI provider is not found → report in status. (like it is being done with the Kuadrant CRD)

Example of how an instance of the TLSPolicy status would look like when cert-manager would not be installed.

```yaml
conditions:
  - lastTransitionTime: "2024-07-04T08:02:09Z"
    message: 'TLSPolicy has encountered some issues: cert-manager APIs not available'
    reason: Unknown
    status: "False"
    type: Accepted
observedGeneration: 1
```
