### ISSUE TITLE
Expose the option for Kuadrant to be installed in HA mode

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#798]
**What**

When you install Kuadrant, it defaults to a single instance of Authorino and Limitador. In order to be resilient to failure, some installations  may want multiple instances of Authorino and Limitador deployed as these components are in the critical path for requests. As Authorino and Limitador support having multiple instances deployed on the same cluster, we should expose options for this deployment topology to be used via Kuadrant

At a high level the key things to expose would be the number of replicas of each that you want and how you want them distributed. 
Kubernetes supports distributing instances of a pod via topology constraints 
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#topology-spread-constraint-examples

One concept for Kuadrant CRD:

```
deployment:
   limitador | ratelimiting:
     replicas: 3
     topologyKey: zone
   authorino | auth:
     replicas: 3
     topologyKey: zone
```

**Done**

- [ ] Decide how to expose this deployment topology via the Kuadrant CR
- [ ] Understand any required changes to the Authorino and Limitador operators
- [ ] Implement the chosen Kuadrant CR and Kuadrant Operator changes
- [ ] Add e2e test that deploys Kuadrant in this shape and tests it is as expected
- [ ] Document the options for this deployment type in the Kuadrant CR
