### ISSUE TITLE
Wasm configuration based on extensions

### ISSUE THREAD

**Issue by eguzki** [Kuadrant/kuadrant-operator#867]
The wasm configuration has changed. Still WIP in branch [external-auth](https://github.com/Kuadrant/wasm-shim/tree/external-auth) and related PR:
* https://github.com/Kuadrant/wasm-shim/pull/81 
* https://github.com/Kuadrant/wasm-shim/pull/87

New configuration, based on extensions, looks like the following:

```yaml
---
extensions:
  limitador:
    type: ratelimit
    endpoint: limitador-cluster
    failureMode: deny
policies:
  - name: rlp-ns-A/rlp-name-A
    hostnames:
      - '*.toystore.com'
      - example.com
    rules:
      - conditions:
          - allOf:
              - selector: request.path
                operator: eq
                value: /admin/toy
              - selector: request.method
                operator: eq
                value: POST
              - selector: request.host
                operator: eq
                value: cars.toystore.com
        actions:
          - extension: limitador
            scope: rlp-ns-A/rlp-name-A
            data:
              - static:
                  key: rlp-ns-A/rlp-name-A
                  value: "1"
              - selector:
                  selector: auth.metadata.username
```

The wasm controllers should be updated to generate the  configuration scheme expected by the wasm module. 

The scope of this issue is limited to rate limiting. External auth using wasm will be covered in following up tasks.

Related issues: https://github.com/Kuadrant/wasm-shim/issues/58
