### ISSUE TITLE
bug: updating DNSPolicy triggers an error updating dnsrecord

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-operator#955]
**What**

using a DNSPolicy such as

```
apiVersion: kuadrant.io/v1alpha1
kind: DNSPolicy
metadata:
  name: external-dnspolicy
spec:
  loadBalancing:
    weight: 122
    geo: EU
    defaultGeo: true
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: external
  providerRefs:
    - name: aws-credentials
  healthCheck:
    path: /health
    port: 443
    protocol: HTTPS
    interval: 30s
    failureThreshold: 3
```

It creates fine and the expected DNSRecord is set up.

Updating any of the fields in the DNSPolicy (example the weight) causes the following error 

```
kuadrant-operator-controller-manager-865b5c8d96-8xqdb manager {"level":"info","ts":"2024-10-24T10:59:13Z","logger":"kuadrant-operator.event logger","msg":"new event","type":"update","kind":"DNSPolicy","namespace":"test","name":"external-dnspolicy"}
kuadrant-operator-controller-manager-865b5c8d96-8xqdb manager {"level":"error","ts":"2024-10-24T10:59:13Z","logger":"kuadrant-operator.EffectiveDNSPoliciesReconciler","msg":"unable to update dns record","policy":"dnspolicy.kuadrant.io:test/external-dnspolicy","listener":"gateway.gateway.networking.k8s.io:test/external#http","record":"dnsrecord.kuadrant.io:test/external-http","stacktrace":"github.com/kuadrant/kuadrant-operator/controllers.(*EffectiveDNSPoliciesReconciler).reconcile\n\t/workspace/controllers/effective_dnspolicies_reconciler.go:172\ngithub.com/kuadrant/policy-machinery/controller.Subscription.Reconcile\n\t/go/pkg/mod/github.com/kuadrant/policy-machinery@v0.6.0/controller/subscriber.go:34\ngithub.com/kuadrant/policy-machinery/controller.(*Workflow).Run.func1\n\t/go/pkg/mod/github.com/kuadrant/policy-machinery@v0.6.0/controller/workflow.go:42\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78"}
```

additionally there is no indication of a problem on DNSPolicy:

```
status:
    conditions:
    - lastTransitionTime: "2024-10-24T10:56:34Z"
      message: DNSPolicy has been accepted
      reason: Accepted
      status: "True"
      type: Accepted
    - lastTransitionTime: "2024-10-24T10:56:39Z"
      message: DNSPolicy has been successfully enforced
      reason: Enforced
      status: "True"
      type: Enforced
    observedGeneration: 2
    totalRecords: 1
```
