### ISSUE TITLE
Crash after adding listener to Gateway

### ISSUE THREAD

**Issue by azgabur** [Kuadrant/kuadrant-operator#990]
I noticed a crash loop of kuadrant-operator pod after adding new listener to Gateway before adding it to associated HTTProute.

Logs:
```
{"level":"error","ts":"2024-11-07T17:24:14Z","logger":"kuadrant-operator.IstioExtensionReconciler.buildWasmConfigs","msg":"failed to build wasm policies for path","pathID":"istio|kuadrant/gw-azgabur--85d|kuadrant/gw-azgabur--85d#api-second|kuadrant/route-azgabur--efth|kuadrant/route-azgabur--efth#rule-1","error":"invalid path: http route does not belong to the listener","stacktrace":"github.com/kuadrant/kuadrant-operator/controllers.(*IstioExtensionReconciler).buildWasmConfigs\n\t/workspace/controllers/istio_extension_reconciler.go:198\ngithub.com/kuadrant/kuadrant-operator/controllers.(*IstioExtensionReconciler).Reconcile\n\t/workspace/controllers/istio_extension_reconciler.go:58\ngithub.com/kuadrant/policy-machinery/controller.Subscription.Reconcile\n\t/go/pkg/mod/github.com/kuadrant/policy-machinery@v0.6.4/controller/subscriber.go:34\ngithub.com/kuadrant/policy-machinery/controller.(*Workflow).Run.func1\n\t/go/pkg/mod/github.com/kuadrant/policy-machinery@v0.6.4/controller/workflow.go:42\ngolang.org/x/sy...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1ab5ffb]
goroutine 4568 [running]:
github.com/kuadrant/kuadrant-operator/controllers.(*AuthConfigsReconciler).Reconcile(0xc0007901e8, {0x23ad5b0, 0xc001da44b0}, {0xc0030623f0?, 0x1?, 0x2?}, 0xc002f907a0, {0x0?, 0x0?}, 0xc002f907c0)
/workspace/controllers/authconfigs_reconciler.go:73 +0x57b
github.com/kuadrant/policy-machinery/controller.Subscription.Reconcile({0xc0002c8af0?, {0xc0004ffc20?, 0xc003217310?, 0xc000aaf830?}}, {0x23ad5b0, 0xc001da44b0}, {0xc000aaf830?, 0x0?, 0x0?}, 0xc002f907a0, ...)
/go/pkg/mod/github.com/kuadrant/policy-machinery@v0.6.4/controller/subscriber.go:34 +0xd9
github.com/kuadrant/policy-machinery/controller.(*Workflow).Run.func1()
/go/pkg/mod/github.com/kuadrant/policy-machinery@v0.6.4/controller/workflow.go:42 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1()
/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x56
```

## Steps to reproduce:

1. Create Gateway object:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw
  namespace: kuadrant
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: prefix1.example.com
      name: api
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: gw-azgabur--85d-tls
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: prefix2.example.com
      name: api-second
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: gw-azgabur--85d-tls
        mode: Terminate
```

2. Create HTTPRoute
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route
  namespace: kuadrant
spec:
  hostnames:
    - prefix1.example.com
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gw
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: httpbin
          namespace: kuadrant
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
```

**Comment by maleck13** [comment]
does this also affect rc4? @azgabur

**Comment by azgabur** [comment]
Yes, I am still observing the error in rc4 as well.

**Comment by maleck13** [comment]
ok any of these issues if you see them still being issues in rc4 can you set the `affected Release`  field then they will show up in our board

**Comment by KevFan** [comment]
@azgabur I'm unable to replicate this locally by following the current steps of creating the resources, can you provide more detailed steps to reproduce, including if there's any policies or the kuadrant cr has been applied? 🙏

**Comment by azgabur** [comment]
Yes, we apply DNSPolicy, TLSPolicy and AuthPolicy. I removed DNS/TLSPolicy to isolate the problem and the crash stayed. After I removed AuthPolicy the crash stopped. So maybe it is relevant. I am posting the AuthPolicy, DNSPolicy and TLSPolicy here:
```
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: authz
  namespace: kuadrant
spec:
  rules:
    authentication:
      default:
        credentials:
          authorizationHeader:
            prefix: Bearer
        jwt:
          issuerUrl: 'http://10.0.140.178:8080/realms/realm-azgabur--spdd'
          ttl: 0
        metrics: false
        priority: 0
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: route
```
```
apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: dns
  namespace: kuadrant
spec:
  providerRefs:
    - name: aws-credentials
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gw
```
```
apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: tls-azgabur--dfom
  namespace: kuadrant
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey: {}
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: gw
status:
  conditions:
    - lastTransitionTime: '2024-11-13T12:34:53Z'
      message: TLSPolicy has been accepted
      reason: Accepted
      status: 'True'
      type: Accepted
    - lastTransitionTime: '2024-11-13T12:38:04Z'
      message: 'TLSPolicy has encountered some issues: certificate gw-api-second is not ready: IncorrectCertificate - Secret was issued for "gw". If this message is not transient, you might have two conflicting Certificates pointing to the same secret.. Shared TLS certificates refs between listeners not supported. Use unique certificates refs in the Gateway listeners to fully enforce policy'
      reason: Unknown
      status: 'False'
      type: Enforced
```

PS. I just noticed the error in TLSPolicy 🤔  (Other CR had no errors)

**Comment by azgabur** [comment]
The TLSPolicy error is not relevant as fixing the cause does not prevent the crashing.

**Comment by KevFan** [comment]
Thanks @azgabur  👍 

On:

> The TLSPolicy error is not relevant as fixing the cause does not prevent the crashing.

This is expected due to the changes for section name support for TLSPolicy from https://github.com/Kuadrant/kuadrant-operator/pull/983. We now **disallow** shared secrets between listeners (i.e. the secret defined in each certificateRefs in the listeners now must be unique) for the `TLSPolicy` to be enforced as we now always create a Certificate per listener instead. So this error on the TLSPolicy status can be resolved by doing this on the Gateway.

For example:
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw
  namespace: kuadrant
spec:
  gatewayClassName: istio
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: prefix1.example.com
      name: api
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: gw-azgabur--85d-tls1
        mode: Terminate
    - allowedRoutes:
        namespaces:
          from: All
      hostname: prefix2.example.com
      name: api-second
      port: 443
      protocol: HTTPS
      tls:
        certificateRefs:
          - group: ''
            kind: Secret
            name: gw-azgabur--85d-tls2
        mode: Terminate
```
