### ISSUE TITLE
Response is not added to response.success.headers

### ISSUE THREAD

**Issue by jsmolar** [Kuadrant/kuadrant-operator#997]
No data is added to the response when `response.success.headers` is used. The response is correctly added when I use the same spec for AuthConfig and standalone authorino.

AuthPolicy:
```
spec:
  rules:
    authentication:
      default:
        credentials:
          authorizationHeader:
            prefix: Bearer
        jwt:
          issuerUrl: 'http://10.0.96.144:8080/realms/realm-jsmolar--ykuo'
          ttl: 0
    response:
      success:
        headers:
          simple:
            json:
              properties:
                data:
                  selector: auth
            metrics: false
            priority: 0
```
I expect that the response to the client would contain `headers.simple` with data from `auth`.
